title: SuperCMS
description: It!
baseURL: /
languageCode: en-ca
menu:
  - main:
      - name: Home
        url: /
        weight: "1"
params:
  - gtm: ""
    servicename: CMS
    schema:
      - ogimage: ""
        logofooter: ""
        logo: ""
        phone: +1-819-219-0502
        priceRange: $$
        address: 123 Rue Labelle
        type: Professional
        openinghour: Mo-9-50
        email: info@supersonicsites.com
        address2: ""
    googlemap: ""
    social:
      - facebook: https://www.facebook.com
        twitter: "/"
        pinterest: ""
        instagram: ""
        linkedin: ""
    hours:
      - hours: Monday 9 to 5
    sitename: SuperCMS
    usebasin: ''
    description: This is it
