baseURL = "https://elopetofino.netlify.app/"
title = "Elope Tofino"
description = "Elopement & Small Wedding planning"
languageCode = "en-ca"
DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"

[build]
writeStats = true
enableRobotsTXT = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = "1"

[[menu.main]]
name = "About"
url = "about/"
weight = "2"

[[menu.main]]
name = "Services"
url = "services/"
weight = "3"

[[menu.main]]
name = "Contact"
url = "contact/"
weight = "4"

[params]
gtm = "#"
servicename = "Small & Elopement Wedding Planning"
googlemap = "#"
sitename = "ElopeTofino"
usebasin = "#"
videoOn = true
description = "We help you make your special day that much more special."

[params.schema]
ogimage = "https://ik.imagekit.io/supersonicsites/ElopeTofino/ElopeTofino_Hero_Shot_zU9eYRaTnY.jpg"
logofooter = "ElopeTofino/ElopeTofino_Logo_d8rEL81lx.png"
city = "Rigaud"
logo = "ElopeTofino/ElopeTofino_Logo_d8rEL81lx.png"
phone = "-"
priceRange = "$$"
region = "QC"
country = "Canada"
postalcode = "J0P 1P0"
type = "ProfessionalServices"
openinghour = "Mo-Su 9:00-21:00"
email = "contact@elopetofino.com"
address1 = "119 Rue Saint-Pierre"
address2 = "#"
address_toggle = false

[params.social]
facebook = "#"
twitter = "#"
pinterest = "#"
instagram = "https://www.instagram.com/elope_tofino/"
linkedin = "#"

[[params.hours]]
hours = "Mon to Sun 9 AM to 9 PM"