backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - label: "Settings"
    name: "settings"
    files:
      - name: "config"
        label: "config.yaml"
        file: "config.yaml"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'BaseURL', name: 'baseURL', widget: 'string', default: "/" }
          - { label: "disableKinds", name: "disabledKinds", widget: "hidden"}
          - { label: "sitemap", name: "sitemap", widget: "hidden"}
          - { label: "build", name: "build", widget: "hidden"}
          - { label: "enableRobotsTXT", name: "enableRobotsTXT", widget: "hidden"}
          - { label: "Language Code", name: "languageCode", widget: "string"}
          - label: "Menu"
            name: "menu"
            widget: "list"
            fields:
              - label: 'Menu Items'
                name: 'main'
                widget: list
                fields:
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'URL', name: 'url', widget: 'string' }
                  - { label: 'Weight', name: 'weight', widget: 'string' }
          - label: "Parameters"
            name: "params"
            widget: "list"
            fields:
              - { label: 'Site Name', name: 'sitename', widget: 'string' }
              - { label: 'Service Name', name: 'servicename', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'UseBasin Endpoint', name: 'usebasin', widget: 'string' }
              - { label: 'Google Map', name: 'googlemap', widget: 'string' }
              - { label: 'Tag Manager ID', name: 'gtm', widget: 'string' }
              - label: "Social Media"
                name: "social"
                widget: "list"
                fields:
                  - { label: 'Facebook', name: 'facebook', widget: 'string' }
                  - { label: 'Twitter', name: 'twitter', widget: 'string' }
                  - { label: 'Pinterest', name: 'pinterest', widget: 'string' }
                  - { label: 'Instagram', name: 'instagram', widget: 'string' }
                  - { label: 'LinkedIn', name: 'linkedin', widget: 'string' }
              - label: "Schema Info"
                name: "schema"
                widget: "list"
                fields:
                  - { label: 'type', name: 'type', widget: 'string' }
                  - { label: 'priceRange', name: 'priceRange', widget: 'string' }
                  - { label: 'Reservation', name: 'reservation', widget: 'boolean', required: false }
                  - { label: 'Opening Hours', name: 'openinghour', widget: 'string' }
                  - { label: 'Logo in Footer', name: 'logofooter', widget: 'string' }
                  - { label: 'Logo', name: 'logo', widget: 'string' }
                  - { label: 'OpenGraph Image', name: 'ogimage', widget: 'string' }
                  - { label: 'Address Line 1', name: 'address', widget: 'string' }
                  - { label: 'Address Line 2', name: 'address2', widget: 'string' }
                  - { label: 'Phone Number', name: 'phone', widget: 'string', default: "+1-" }
                  - { label: 'Email Address', name: 'email', widget: 'string' }
              - label: "Business Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: 'Enter Hour', name: 'hours', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    folder: 'content/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "SEO Title Max 45 characters", name: "title", widget: "string" }
      - { label: "SEO Description Max 120 characters", name: "description", widget: "string" }
      - label: "Components"
        label_singular: "component"
        name: "components"
        widget: "list"
        types:
          - label: "4 Columns Text Cards"
            name: "cards_fourth_text"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "SHADOW ON/OFF", name: "shadow_select", widget: "boolean", required: false }
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Title ON/OFF", name: "title_select", widget: "boolean", required: false }
                    - { label: "Title Size", name: "title_size", widget: "select", options: ["small", "medium", "big"] }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Title Color", name: "title_color", widget: "string", default: "black" }
                    - { label: "Subtitle ON/OFF", name: "subtitle_select", widget: "boolean", required: false }
                    - { label: "Subtitle", name: "subtitle", widget: "string" }
                    - { label: "Divider ON/OFF", name: "divider_select", widget: "boolean", required: false }
                    - { label: "Divider Color", name: "divider_color", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string" }
                    - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "4 Columns Icon Cards"
            name: "cards_fourth_icon"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Icon", name: "icon", widget: "string" }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string" }
                    - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "4 Columns Image Cards"
            name: "cards_fourth_img"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Image", name: "img", widget: "string", default: "DEV/boilerplate-bg_tRB-gJlPq.jpg" }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string", default: "Call To Action" }
                    - { label: "CTA Link", name: "cta_link", widget: "string", default: "contact/" }
          - label: "3 Columns Text Cards"
            name: "cards_third_text"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "SHADOW ON/OFF", name: "shadow_select", widget: "boolean", required: false }
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Title ON/OFF", name: "title_select", widget: "boolean", required: false }
                    - { label: "Title Size", name: "title_size", widget: "select", options: ["small", "medium", "big"] }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Title Color", name: "title_color", widget: "string", default: "black" }
                    - { label: "Subtitle ON/OFF", name: "subtitle_select", widget: "boolean", required: false }
                    - { label: "Subtitle", name: "subtitle", widget: "string" }
                    - { label: "Divider ON/OFF", name: "divider_select", widget: "boolean", required: false }
                    - { label: "Divider Color", name: "divider_color", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string" }
                    - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "3 Columns Icon Cards"
            name: "cards_third_icon"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Icon", name: "icon", widget: "string" }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string", default: "Call To Action" }
                    - { label: "CTA Link", name: "cta_link", widget: "string", default: "contact/" }
          - label: "3 Columns Image Cards"
            name: "cards_third_img"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Image", name: "img", widget: "string", default: "DEV/boilerplate-bg_tRB-gJlPq.jpg" }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string", default: "Call To Action" }
                    - { label: "CTA Link", name: "cta_link", widget: "string", default: "contact/" }
          - label: "2 Columns Text Cards"
            name: "cards_half_text"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "SHADOW ON/OFF", name: "shadow_select", widget: "boolean", required: false }
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Title ON/OFF", name: "title_select", widget: "boolean", required: false }
                    - { label: "Title Size", name: "title_size", widget: "select", options: ["small", "medium", "big"] }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Title Color", name: "title_color", widget: "string", default: "black" }
                    - { label: "Subtitle ON/OFF", name: "subtitle_select", widget: "boolean", required: false }
                    - { label: "Subtitle", name: "subtitle", widget: "string" }
                    - { label: "Divider ON/OFF", name: "divider_select", widget: "boolean", required: false }
                    - { label: "Divider Color", name: "divider_color", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string" }
                    - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "2 Columns Icon Cards"
            name: "cards_half_icon"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Icon", name: "icon", widget: "string" }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string" }
                    - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "2 Columns Image Cards"
            name: "cards_half_img"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - label: "Cards"
                  name: "cards"
                  label_singular: "card"
                  widget: "list"
                  fields: 
                    - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
                    - { label: "AOS", name: "aos", widget: "string" }
                    - { label: "Image", name: "img", widget: "string", default: "DEV/boilerplate-bg_tRB-gJlPq.jpg" }
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Description", name: "desc", widget: "string" }
                    - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
                    - { label: "CTA", name: "cta", widget: "string", default: "Call To Action" }
                    - { label: "CTA Link", name: "cta_link", widget: "string", default: "contact/" }
          - label: "Heading Fullwidth"
            name: "heading_full"
            widget: "object"
            fields:
              - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
              - { label: "Title Size", name: "title_size", widget: "select", options: ["small", "medium", "big"] }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description ON/OFF", name: "desc_select", widget: "boolean", required: false }
              - { label: "Description", name: "desc", widget: "string" }
          - label: "2 Columns Image Left"
            name: "img_half_left"
            widget: "object"
            fields:
              - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
              - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
              - { label: "AOS", name: "aos", widget: "string" }
              - { label: "Image", name: "img", widget: "string", default: "DEV/boilerplate-bg_tRB-gJlPq.jpg" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
              - { label: "CTA", name: "cta", widget: "string", default: "Call To Action" }
              - { label: "CTA Link", name: "cta_link", widget: "string", default: "contact/" }
          - label: "2 Columns Image Right"
            name: "img_half_right"
            widget: "object"
            fields:
              - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
              - { label: "AOS ON/OFF", name: "aos_select", widget: "boolean", required: false }
              - { label: "AOS", name: "aos", widget: "string" }
              - { label: "Image", name: "img", widget: "string", default: "DEV/boilerplate-bg_tRB-gJlPq.jpg" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "CTA ON/OFF", name: "cta_select", widget: "boolean", required: false }
              - { label: "CTA", name: "cta", widget: "string", default: "Call To Action" }
              - { label: "CTA Link", name: "cta_link", widget: "string", default: "contact/" }
          - label: "Subheader"
            name: "header_sub"
            widget: "object"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Image", name: "img", widget: "string", default: "DEV/boilerplate-bg_tRB-gJlPq.jpg" }
          - label: "Small Divider"
            name: "divider_half"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
          - label: "Divider"
            name: "divider"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
          - label: "Large Divider"
            name: "divider2x"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
          - label: "Call to Action Bar"
            name: "cta"
            widget: "object"
            fields:
                - { label: "Background Color", name: "bg_color", widget: "string", default: "white" }
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Call to Action Text", name: "cta", widget: "string" }
                - { label: "Call to Action Link", name: "cta_link", widget: "string" }