backend:
  name: git-gateway
  branch: main


local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'content/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: "Components"
        label_singular: "component"
        name: "components"
        widget: "list"
        types:
<<<<<<< HEAD
          - label: "header_sub"
=======
          - label: "Subheader"
>>>>>>> c56d5fbb831023d7a5eea68d6dd52ccd63bab45f
            name: "header_sub"
            widget: "object"
            fields:
                - { label: "Title", name: "title", widget: "string" }
<<<<<<< HEAD
                - { label: "Image", name: "img", widget: "string" }
=======
                - { label: "Image", name: "img", widget: "image" }
>>>>>>> c56d5fbb831023d7a5eea68d6dd52ccd63bab45f
